export const PATHS = {
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  USERS_CREATE: '/users/create',
  USERS_EDIT: '/users/:id/edit',
  USERS_VIEW: '/users/:id',
  ROLES: '/roles',
  ROLES_CREATE: '/roles/create',
  ROLES_EDIT: '/roles/:id/edit',
  ROLES_PERMISSIONS: '/roles/:id/permissions',
  PERMISSIONS: '/permissions',
  PERMISSIONS_CREATE: '/permissions/create',
  PERMISSIONS_EDIT: '/permissions/:id/edit',
  AREAS: '/areas',
  AREAS_CREATE: '/areas/new',
  AREAS_EDIT: '/areas/:id/edit',
  AREAS_VIEW: '/areas/:id',
  PRODUCTION_AREAS: '/production-areas',
  PRODUCTION_AREAS_CREATE: '/production-areas/new',
  PRODUCTION_AREAS_EDIT: '/production-areas/:id/edit',
  PRODUCTION_AREAS_VIEW: '/production-areas/:id',
  CARGOS: '/cargos',
  CARGOS_CREATE: '/cargos/new',
  CARGOS_EDIT: '/cargos/:id/edit',
  CARGOS_VIEW: '/cargos/:id',
  AUDIT_LOGS: '/audit-logs',
  SETTINGS: '/settings',
  PROFILE: '/settings/profile',
  NOT_FOUND: '/not-found',
  UNAUTHORIZED: '/unauthorized',
  CLIENTS: '/clients',
  CLIENTS_CREATE: '/clients/new',
  CLIENTS_EDIT: '/clients/:id/edit',
  CLIENTS_VIEW: '/clients/:id',
  SUPPLIERS: '/suppliers',
  SUPPLIERS_CREATE: '/suppliers/new',
  SUPPLIERS_EDIT: '/suppliers/:id/edit',
  SUPPLIERS_VIEW: '/suppliers/:id',
  SESSION_LOGS: '/session-logs',
  // Portfolio Routes
  UNITS_OF_MEASURE: '/portfolio/units-of-measure',
  UNITS_OF_MEASURE_CREATE: '/portfolio/units-of-measure/new',
  UNITS_OF_MEASURE_EDIT: '/portfolio/units-of-measure/:id/edit',
  PRODUCT_CATEGORIES: '/portfolio/product-categories',
  PRODUCT_CATEGORIES_CREATE: '/portfolio/product-categories/new',
  PRODUCT_CATEGORIES_EDIT: '/portfolio/product-categories/:id/edit',
  PRODUCTS: '/portfolio/products',
  PRODUCTS_CREATE: '/portfolio/products/new',
  PRODUCTS_EDIT: '/portfolio/products/:id/edit',
  SUPPLY_CATEGORIES: '/portfolio/supply-categories',
  SUPPLY_CATEGORIES_CREATE: '/portfolio/supply-categories/new',
  SUPPLY_CATEGORIES_EDIT: '/portfolio/supply-categories/:id/edit',
  SUPPLIES: '/portfolio/supplies',
  SUPPLIES_CREATE: '/portfolio/supplies/new',
  SUPPLIES_EDIT: '/portfolio/supplies/:id/edit',
  // Orders Routes
  ORDERS: '/orders',
  ORDERS_CREATE: '/orders/new',
  ORDERS_EDIT: '/orders/:id/edit',
  ORDERS_DETAIL: '/orders/:id',
  PENDING_PAYMENT_ORDERS: '/orders/pending-payment',
  STATUS_CHANGE_REQUESTS: '/orders/status-change-requests',
  // Order Timeline
  ORDER_FLOW: '/orders/flow/:type/:id',
  ORDER_FLOW_BASE: '/orders/flow',
  // Quotes Routes
  QUOTES: '/quotes',
  QUOTES_CREATE: '/quotes/new',
  QUOTES_EDIT: '/quotes/:id/edit',
  QUOTES_DETAIL: '/quotes/:id',
  // Commercial Channels Routes
  COMMERCIAL_CHANNELS: '/commercial-channels',
  COMMERCIAL_CHANNELS_CREATE: '/commercial-channels/new',
  COMMERCIAL_CHANNELS_EDIT: '/commercial-channels/:id/edit',
  COMMERCIAL_CHANNELS_VIEW: '/commercial-channels/:id',
  NOTIFICATIONS: '/notifications',
  // Company
  COMPANY: '/company',
  // Work Orders Routes
  WORK_ORDERS: '/work-orders',
  WORK_ORDERS_CREATE: '/work-orders/new',
  WORK_ORDERS_EDIT: '/work-orders/:id/edit',
  WORK_ORDERS_DETAIL: '/work-orders/:id',
  // Expense Orders Routes
  EXPENSE_ORDERS: '/expense-orders',
  EXPENSE_ORDERS_CREATE: '/expense-orders/new',
  EXPENSE_ORDERS_EDIT: '/expense-orders/:id/edit',
  EXPENSE_ORDERS_DETAIL: '/expense-orders/:id',
};

