export const PATHS = {
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  USERS_CREATE: '/users/create',
  USERS_EDIT: '/users/:id/edit',
  USERS_VIEW: '/users/:id',
  ROLES: '/roles',
  ROLES_CREATE: '/roles/create',
  ROLES_EDIT: '/roles/:id/edit',
  ROLES_PERMISSIONS: '/roles/:id/permissions',
  PERMISSIONS: '/permissions',
  PERMISSIONS_CREATE: '/permissions/create',
  PERMISSIONS_EDIT: '/permissions/:id/edit',
  AREAS: '/areas',
  AREAS_CREATE: '/areas/new',
  AREAS_EDIT: '/areas/:id/edit',
  AREAS_VIEW: '/areas/:id',
  CARGOS: '/cargos',
  CARGOS_CREATE: '/cargos/new',
  CARGOS_EDIT: '/cargos/:id/edit',
  CARGOS_VIEW: '/cargos/:id',
  AUDIT_LOGS: '/audit-logs',
  NOT_FOUND: '/not-found',
  UNAUTHORIZED: '/unauthorized',
};

