export const PATHS = {
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  USERS_CREATE: '/users/create',
  USERS_EDIT: '/users/:id/edit',
  USERS_VIEW: '/users/:id',
  ROLES: '/roles',
  ROLES_CREATE: '/roles/create',
  ROLES_EDIT: '/roles/:id/edit',
  PERMISSIONS: '/permissions',
  PERMISSIONS_CREATE: '/permissions/create',
  NOT_FOUND: '/not-found',
  UNAUTHORIZED: '/unauthorized',
};
