export interface SearchItem {
  id: string;
  label: string;
  subtitle?: string;
  category: 'modulo' | 'accion' | 'configuracion';
  icon: string;
  path: string;
  keywords: string[];
  permission?: string;
  permissions?: string[];
}

export const SEARCH_REGISTRY: SearchItem[] = [
  // ─── MÓDULOS ─────────────────────────────────────────────────────────────────
  {
    id: 'dashboard',
    label: 'Dashboard',
    subtitle: 'Resumen general del sistema',
    category: 'modulo',
    icon: 'Dashboard',
    path: '/dashboard',
    keywords: ['dashboard', 'inicio', 'home', 'resumen', 'principal', 'panel'],
  },
  {
    id: 'clients',
    label: 'Clientes',
    subtitle: 'Gestión de clientes',
    category: 'modulo',
    icon: 'People',
    path: '/clients',
    keywords: ['clientes', 'cliente', 'customers', 'contactos'],
    permission: 'read_clients',
  },
  {
    id: 'suppliers',
    label: 'Proveedores',
    subtitle: 'Gestión de proveedores',
    category: 'modulo',
    icon: 'LocalShipping',
    path: '/suppliers',
    keywords: ['proveedores', 'proveedor', 'suppliers', 'vendors'],
    permission: 'read_suppliers',
  },
  {
    id: 'orders',
    label: 'Órdenes de Pedido',
    subtitle: 'Listado de órdenes',
    category: 'modulo',
    icon: 'ShoppingCart',
    path: '/orders',
    keywords: ['ordenes', 'orden', 'pedido', 'pedidos', 'op', 'orders', 'venta', 'ventas'],
    permission: 'read_orders',
  },
  {
    id: 'quotes',
    label: 'Cotizaciones',
    subtitle: 'Listado de cotizaciones',
    category: 'modulo',
    icon: 'RequestQuote',
    path: '/quotes',
    keywords: ['cotizaciones', 'cotizacion', 'cotizar', 'presupuesto', 'quotes', 'propuesta'],
    permission: 'read_quotes',
  },
  {
    id: 'work-orders',
    label: 'Órdenes de Trabajo',
    subtitle: 'Gestión de órdenes de trabajo',
    category: 'modulo',
    icon: 'Assignment',
    path: '/work-orders',
    keywords: ['ordenes de trabajo', 'orden de trabajo', 'ot', 'trabajo', 'work orders'],
    permission: 'read_work_orders',
  },
  {
    id: 'expense-orders',
    label: 'Órdenes de Gasto',
    subtitle: 'Registro de gastos',
    category: 'modulo',
    icon: 'Receipt',
    path: '/expense-orders',
    keywords: ['gastos', 'gasto', 'ordenes de gasto', 'egresos', 'expenses'],
    permission: 'read_expense_orders',
  },
  {
    id: 'commercial-channels',
    label: 'Canales Comerciales',
    subtitle: 'Canales de venta',
    category: 'modulo',
    icon: 'Campaign',
    path: '/commercial-channels',
    keywords: ['canales', 'canal', 'comercial', 'comerciales', 'venta', 'channels'],
    permission: 'read_commercial_channels',
  },
  {
    id: 'production-orders',
    label: 'Producción',
    subtitle: 'Órdenes de producción',
    category: 'modulo',
    icon: 'Factory',
    path: '/production/orders',
    keywords: ['produccion', 'producción', 'fabricacion', 'manufactura', 'production', 'ordenes produccion'],
    permission: 'read_production_orders',
  },
  {
    id: 'production-templates',
    label: 'Plantillas de Producción',
    subtitle: 'Plantillas y recetas',
    category: 'modulo',
    icon: 'Description',
    path: '/production/templates',
    keywords: ['plantillas', 'plantilla', 'templates', 'recetas', 'produccion plantilla'],
    permission: 'read_production_orders',
  },
  {
    id: 'pending-payment-orders',
    label: 'Órdenes Pendientes de Pago',
    subtitle: 'Órdenes sin cobro',
    category: 'modulo',
    icon: 'PaymentOutlined',
    path: '/orders/pending-payment',
    keywords: ['pendiente', 'pendientes', 'pago', 'cobro', 'sin pagar', 'deuda'],
    permission: 'read_orders',
  },
  {
    id: 'orders-profitability',
    label: 'Rentabilidad de Órdenes',
    subtitle: 'Análisis de rentabilidad',
    category: 'modulo',
    icon: 'TrendingUp',
    path: '/orders/profitability',
    keywords: ['rentabilidad', 'rentable', 'margen', 'ganancias', 'profitability'],
    permission: 'read_orders',
  },
  {
    id: 'status-change-requests',
    label: 'Solicitudes de Cambio de Estado',
    subtitle: 'Aprobaciones pendientes',
    category: 'modulo',
    icon: 'ChangeCircle',
    path: '/orders/status-change-requests',
    keywords: ['solicitudes', 'cambio de estado', 'aprobacion', 'aprobaciones', 'estado'],
    permission: 'read_orders',
  },
  {
    id: 'cash-registers',
    label: 'Caja Registradora',
    subtitle: 'Administración de cajas',
    category: 'modulo',
    icon: 'PointOfSale',
    path: '/cash-register/admin',
    keywords: ['caja', 'cajas', 'pos', 'registradora', 'cash register', 'punto de venta'],
    permission: 'manage_cash_registers',
  },
  {
    id: 'cash-session-history',
    label: 'Historial de Sesiones de Caja',
    subtitle: 'Sesiones anteriores',
    category: 'modulo',
    icon: 'History',
    path: '/cash-register/history',
    keywords: ['historial caja', 'sesiones caja', 'caja historial', 'cierre caja'],
    permission: 'read_cash_sessions',
  },
  {
    id: 'accounts-payable',
    label: 'Cuentas por Pagar',
    subtitle: 'Pasivos y pagos a proveedores',
    category: 'modulo',
    icon: 'AccountBalance',
    path: '/accounts-payable',
    keywords: ['cuentas por pagar', 'cxp', 'pasivos', 'proveedores pago', 'deudas'],
    permission: 'read_accounts_payable',
  },
  {
    id: 'payroll-employees',
    label: 'Empleados',
    subtitle: 'Nómina — listado de empleados',
    category: 'modulo',
    icon: 'Badge',
    path: '/payroll/employees',
    keywords: ['empleados', 'empleado', 'nomina', 'nómina', 'trabajadores', 'personal', 'rrhh'],
    permission: 'read_payroll',
  },
  {
    id: 'payroll-periods',
    label: 'Períodos de Nómina',
    subtitle: 'Gestión de períodos de pago',
    category: 'modulo',
    icon: 'DateRange',
    path: '/payroll/periods',
    keywords: ['periodos', 'período', 'nomina', 'nómina', 'liquidacion', 'pago empleados'],
    permission: 'read_payroll',
  },
  {
    id: 'inventory-movements',
    label: 'Inventario',
    subtitle: 'Movimientos de inventario',
    category: 'modulo',
    icon: 'Inventory',
    path: '/inventory/movements',
    keywords: ['inventario', 'stock', 'movimientos', 'bodega', 'almacen', 'inventory'],
    permission: 'read_inventory',
  },
  {
    id: 'inventory-low-stock',
    label: 'Stock Bajo',
    subtitle: 'Productos con stock mínimo',
    category: 'modulo',
    icon: 'WarningAmber',
    path: '/inventory/low-stock',
    keywords: ['stock bajo', 'minimo', 'agotado', 'reposicion', 'low stock', 'alerta inventario'],
    permission: 'read_inventory',
  },
  {
    id: 'products',
    label: 'Productos',
    subtitle: 'Portafolio de productos',
    category: 'modulo',
    icon: 'Inventory2',
    path: '/portfolio/products',
    keywords: ['productos', 'producto', 'portafolio', 'catalogo', 'items', 'articulos'],
    permission: 'read_portfolio',
  },
  {
    id: 'product-categories',
    label: 'Categorías de Productos',
    subtitle: 'Clasificación de productos',
    category: 'modulo',
    icon: 'Category',
    path: '/portfolio/product-categories',
    keywords: ['categorias', 'categoria', 'clasificacion', 'grupos productos'],
    permission: 'read_portfolio',
  },
  {
    id: 'supplies',
    label: 'Insumos',
    subtitle: 'Materias primas y materiales',
    category: 'modulo',
    icon: 'Science',
    path: '/portfolio/supplies',
    keywords: ['insumos', 'insumo', 'materiales', 'materia prima', 'supplies', 'componentes'],
    permission: 'read_portfolio',
  },
  {
    id: 'units-of-measure',
    label: 'Unidades de Medida',
    subtitle: 'Configuración de unidades',
    category: 'modulo',
    icon: 'Straighten',
    path: '/portfolio/units-of-measure',
    keywords: ['unidades', 'unidad', 'medida', 'kg', 'litros', 'metros', 'uom'],
    permission: 'read_portfolio',
  },
  {
    id: 'production-areas',
    label: 'Áreas de Producción',
    subtitle: 'Secciones del proceso productivo',
    category: 'modulo',
    icon: 'AccountTree',
    path: '/production-areas',
    keywords: ['areas', 'area', 'produccion', 'secciones', 'proceso', 'planta'],
    permission: 'read_production_areas',
  },
  {
    id: 'attendance',
    label: 'Control de Asistencia',
    subtitle: 'Registros de asistencia del equipo',
    category: 'modulo',
    icon: 'AccessTime',
    path: '/attendance',
    keywords: ['asistencia', 'control asistencia', 'tiempo', 'horario', 'attendance', 'registro'],
    permission: 'read_attendance',
  },
  {
    id: 'notifications',
    label: 'Notificaciones',
    subtitle: 'Centro de notificaciones',
    category: 'modulo',
    icon: 'Notifications',
    path: '/notifications',
    keywords: ['notificaciones', 'alertas', 'avisos', 'notifications'],
  },
  {
    id: 'settings',
    label: 'Configuración',
    subtitle: 'Ajustes del sistema',
    category: 'modulo',
    icon: 'Settings',
    path: '/settings',
    keywords: ['configuracion', 'ajustes', 'settings', 'preferencias'],
  },
  {
    id: 'company',
    label: 'Información de Compañía',
    subtitle: 'Datos de la empresa',
    category: 'modulo',
    icon: 'Business',
    path: '/company',
    keywords: ['compania', 'empresa', 'company', 'organizacion', 'datos empresa', 'nit'],
    permission: 'read_company',
  },

  // ─── ACCIONES ─────────────────────────────────────────────────────────────────
  {
    id: 'action-create-client',
    label: 'Crear Cliente',
    subtitle: 'Registrar nuevo cliente',
    category: 'accion',
    icon: 'PersonAdd',
    path: '/clients/new',
    keywords: ['crear cliente', 'nuevo cliente', 'agregar cliente', 'registrar cliente', 'alta cliente'],
    permission: 'create_clients',
  },
  {
    id: 'action-create-order',
    label: 'Crear Orden de Pedido',
    subtitle: 'Nueva orden de pedido',
    category: 'accion',
    icon: 'AddShoppingCart',
    path: '/orders/new',
    keywords: ['crear orden', 'nueva orden', 'nuevo pedido', 'crear pedido', 'nueva op', 'hacer pedido'],
    permission: 'create_orders',
  },
  {
    id: 'action-create-quote',
    label: 'Crear Cotización',
    subtitle: 'Nueva cotización',
    category: 'accion',
    icon: 'NoteAdd',
    path: '/quotes/new',
    keywords: ['crear cotizacion', 'nueva cotizacion', 'cotizar', 'hacer cotizacion', 'presupuesto nuevo'],
    permission: 'create_quotes',
  },
  {
    id: 'action-create-work-order',
    label: 'Crear Orden de Trabajo',
    subtitle: 'Nueva OT',
    category: 'accion',
    icon: 'AssignmentAdd',
    path: '/work-orders/new',
    keywords: ['crear ot', 'nueva orden trabajo', 'crear orden de trabajo', 'nueva ot'],
    permission: 'create_work_orders',
  },
  {
    id: 'action-create-supplier',
    label: 'Crear Proveedor',
    subtitle: 'Registrar nuevo proveedor',
    category: 'accion',
    icon: 'AddBusiness',
    path: '/suppliers/new',
    keywords: ['crear proveedor', 'nuevo proveedor', 'agregar proveedor', 'registrar proveedor'],
    permission: 'create_suppliers',
  },
  {
    id: 'action-create-product',
    label: 'Crear Producto',
    subtitle: 'Agregar producto al portafolio',
    category: 'accion',
    icon: 'AddBox',
    path: '/portfolio/products/new',
    keywords: ['crear producto', 'nuevo producto', 'agregar producto', 'alta producto'],
    permission: 'create_portfolio',
  },
  {
    id: 'action-create-supply',
    label: 'Crear Insumo',
    subtitle: 'Agregar nuevo insumo',
    category: 'accion',
    icon: 'Science',
    path: '/portfolio/supplies/new',
    keywords: ['crear insumo', 'nuevo insumo', 'agregar insumo', 'nuevo material'],
    permission: 'create_portfolio',
  },
  {
    id: 'action-create-expense-order',
    label: 'Nueva Orden de Gasto',
    subtitle: 'Registrar gasto',
    category: 'accion',
    icon: 'ReceiptLong',
    path: '/expense-orders/new',
    keywords: ['crear gasto', 'nuevo gasto', 'registrar gasto', 'nueva orden gasto'],
    permission: 'create_expense_orders',
  },
  {
    id: 'action-create-production-order',
    label: 'Nueva Orden de Producción',
    subtitle: 'Crear orden de fabricación',
    category: 'accion',
    icon: 'PrecisionManufacturing',
    path: '/production/orders/new',
    keywords: ['crear produccion', 'nueva orden produccion', 'fabricar', 'nueva fabricacion'],
    permission: 'create_production_orders',
  },
  {
    id: 'action-create-production-template',
    label: 'Nueva Plantilla de Producción',
    subtitle: 'Crear receta o plantilla',
    category: 'accion',
    icon: 'PostAdd',
    path: '/production/templates/new',
    keywords: ['crear plantilla', 'nueva plantilla', 'nueva receta', 'crear receta produccion'],
    permission: 'create_production_orders',
  },
  {
    id: 'action-create-employee',
    label: 'Crear Empleado',
    subtitle: 'Registrar nuevo empleado',
    category: 'accion',
    icon: 'PersonAdd',
    path: '/payroll/employees/create',
    keywords: ['crear empleado', 'nuevo empleado', 'registrar empleado', 'alta empleado', 'contratar'],
    permission: 'create_payroll',
  },
  {
    id: 'action-create-payroll-period',
    label: 'Crear Período de Nómina',
    subtitle: 'Nuevo período de liquidación',
    category: 'accion',
    icon: 'CalendarMonth',
    path: '/payroll/periods/create',
    keywords: ['crear periodo', 'nuevo periodo nomina', 'liquidacion nomina', 'pago nomina'],
    permission: 'create_payroll',
  },
  {
    id: 'action-new-inventory-movement',
    label: 'Nuevo Movimiento de Inventario',
    subtitle: 'Entrada o salida de stock',
    category: 'accion',
    icon: 'MoveToInbox',
    path: '/inventory/movements/new',
    keywords: ['movimiento inventario', 'entrada stock', 'salida stock', 'ajuste inventario', 'nuevo movimiento'],
    permission: 'create_inventory',
  },
  {
    id: 'action-create-accounts-payable',
    label: 'Nueva Cuenta por Pagar',
    subtitle: 'Registrar deuda o pasivo',
    category: 'accion',
    icon: 'AddCard',
    path: '/accounts-payable/new',
    keywords: ['nueva cuenta pagar', 'crear cxp', 'registrar deuda', 'nuevo pasivo'],
    permission: 'create_accounts_payable',
  },
  {
    id: 'action-open-cash-session',
    label: 'Abrir Sesión de Caja',
    subtitle: 'Iniciar turno en caja',
    category: 'accion',
    icon: 'LockOpen',
    path: '/cash-register/open',
    keywords: ['abrir caja', 'iniciar caja', 'turno caja', 'apertura caja'],
    permission: 'manage_cash_registers',
  },
  {
    id: 'action-profile',
    label: 'Mi Perfil',
    subtitle: 'Ver y editar tu perfil',
    category: 'accion',
    icon: 'ManageAccounts',
    path: '/settings/profile',
    keywords: ['mi perfil', 'perfil', 'profile', 'mi cuenta', 'datos personales'],
  },

  // ─── CONFIGURACIÓN ────────────────────────────────────────────────────────────
  {
    id: 'users',
    label: 'Usuarios',
    subtitle: 'Gestión de usuarios del sistema',
    category: 'configuracion',
    icon: 'SupervisorAccount',
    path: '/users',
    keywords: ['usuarios', 'usuario', 'users', 'cuentas', 'acceso'],
    permission: 'read_users',
  },
  {
    id: 'roles',
    label: 'Roles',
    subtitle: 'Gestión de roles y permisos',
    category: 'configuracion',
    icon: 'AdminPanelSettings',
    path: '/roles',
    keywords: ['roles', 'rol', 'roles sistema', 'perfiles'],
    permission: 'read_roles',
  },
  {
    id: 'permissions',
    label: 'Permisos',
    subtitle: 'Permisos del sistema',
    category: 'configuracion',
    icon: 'Key',
    path: '/permissions',
    keywords: ['permisos', 'permiso', 'permissions', 'accesos'],
    permission: 'read_permissions',
  },
  {
    id: 'audit-logs',
    label: 'Logs de Auditoría',
    subtitle: 'Historial de actividad',
    category: 'configuracion',
    icon: 'ManageSearch',
    path: '/audit-logs',
    keywords: ['logs', 'auditoria', 'auditoría', 'historial', 'actividad', 'trazabilidad', 'audit'],
    permission: 'read_audit_logs',
  },
  {
    id: 'session-logs',
    label: 'Sesiones de Usuario',
    subtitle: 'Historial de inicio de sesión',
    category: 'configuracion',
    icon: 'VpnKey',
    path: '/session-logs',
    keywords: ['sesiones', 'session', 'login historial', 'accesos usuarios', 'session logs'],
    permission: 'read_session_logs',
  },
  {
    id: 'cargos',
    label: 'Cargos',
    subtitle: 'Cargos y posiciones de trabajo',
    category: 'configuracion',
    icon: 'Work',
    path: '/cargos',
    keywords: ['cargos', 'cargo', 'posiciones', 'puestos', 'jobs', 'roles laborales'],
    permission: 'read_cargos',
  },
  {
    id: 'step-definitions',
    label: 'Definiciones de Pasos',
    subtitle: 'Flujos de producción',
    category: 'configuracion',
    icon: 'Schema',
    path: '/production/step-definitions',
    keywords: ['pasos', 'paso', 'step', 'definiciones', 'flujo produccion', 'proceso produccion'],
    permission: 'read_production_orders',
  },
  {
    id: 'supply-categories',
    label: 'Categorías de Insumos',
    subtitle: 'Clasificación de insumos',
    category: 'configuracion',
    icon: 'Category',
    path: '/portfolio/supply-categories',
    keywords: ['categorias insumos', 'categoria insumo', 'clasificacion insumos'],
    permission: 'read_portfolio',
  },
];

export const CATEGORY_LABELS: Record<SearchItem['category'], string> = {
  modulo: 'Módulos',
  accion: 'Acciones',
  configuracion: 'Configuración',
};

export function scoreItem(item: SearchItem, query: string): number {
  const q = query.toLowerCase().trim();
  if (!q) return 1;
  const words = q.split(/\s+/);
  const labelLow = item.label.toLowerCase();
  const keywordsLow = item.keywords.join(' ').toLowerCase();
  const subtitleLow = (item.subtitle ?? '').toLowerCase();

  let score = 0;
  for (const word of words) {
    if (labelLow.includes(word)) score += 3;
    if (keywordsLow.includes(word)) score += 2;
    if (subtitleLow.includes(word)) score += 1;
  }
  return score;
}
