export const STORAGE_KEYS = {
  ACCESS_TOKEN: 'accessToken',
  REFRESH_TOKEN: 'refreshToken',
  USER: 'user',
  THEME: 'theme',
};

export const PERMISSIONS = {
  CREATE_USERS: 'create_users',
  READ_USERS: 'read_users',
  UPDATE_USERS: 'update_users',
  DELETE_USERS: 'delete_users',
  CREATE_ROLES: 'create_roles',
  READ_ROLES: 'read_roles',
  UPDATE_ROLES: 'update_roles',
  DELETE_ROLES: 'delete_roles',
  CREATE_PERMISSIONS: 'create_permissions',
  READ_PERMISSIONS: 'read_permissions',
  UPDATE_PERMISSIONS: 'update_permissions',
  DELETE_PERMISSIONS: 'delete_permissions',
  MANAGE_PERMISSIONS: 'manage_permissions',
  CREATE_AREAS: 'create_areas',
  READ_AREAS: 'read_areas',
  UPDATE_AREAS: 'update_areas',
  DELETE_AREAS: 'delete_areas',
  CREATE_CARGOS: 'create_cargos',
  READ_CARGOS: 'read_cargos',
  UPDATE_CARGOS: 'update_cargos',
  DELETE_CARGOS: 'delete_cargos',
  READ_AUDIT_LOGS: 'read_audit_logs',
  READ_SESSION_LOGS: 'read_session_logs',
  CREATE_SUPPLIERS: 'create_suppliers',
  READ_SUPPLIERS: 'read_suppliers',
  UPDATE_SUPPLIERS: 'update_suppliers',
  DELETE_SUPPLIERS: 'delete_suppliers',
  CREATE_CLIENTS: 'create_clients',
  READ_CLIENTS: 'read_clients',
  UPDATE_CLIENTS: 'update_clients',
  DELETE_CLIENTS: 'delete_clients',
  // Portfolio - Units of Measure
  CREATE_UNITS_OF_MEASURE: 'create_units_of_measure',
  READ_UNITS_OF_MEASURE: 'read_units_of_measure',
  UPDATE_UNITS_OF_MEASURE: 'update_units_of_measure',
  DELETE_UNITS_OF_MEASURE: 'delete_units_of_measure',
  // Portfolio - Service Categories
  CREATE_SERVICE_CATEGORIES: 'create_service_categories',
  READ_SERVICE_CATEGORIES: 'read_service_categories',
  UPDATE_SERVICE_CATEGORIES: 'update_service_categories',
  DELETE_SERVICE_CATEGORIES: 'delete_service_categories',
  // Portfolio - Services
  CREATE_SERVICES: 'create_services',
  READ_SERVICES: 'read_services',
  UPDATE_SERVICES: 'update_services',
  DELETE_SERVICES: 'delete_services',
};

export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  USERS_CREATE: '/users/create',
  USERS_EDIT: '/users/:id/edit',
  USERS_VIEW: '/users/:id',
  ROLES: '/roles',
  ROLES_CREATE: '/roles/create',
  ROLES_EDIT: '/roles/:id/edit',
  ROLES_PERMISSIONS: '/roles/:id/permissions',
  PERMISSIONS: '/permissions',
  PERMISSIONS_CREATE: '/permissions/create',
  PERMISSIONS_EDIT: '/permissions/:id/edit',
  AREAS: '/areas',
  AREAS_CREATE: '/areas/new',
  AREAS_EDIT: '/areas/:id/edit',
  AREAS_VIEW: '/areas/:id',
  CARGOS: '/cargos',
  CARGOS_CREATE: '/cargos/new',
  CARGOS_EDIT: '/cargos/:id/edit',
  CARGOS_VIEW: '/cargos/:id',
  AUDIT_LOGS: '/audit-logs',
  SESSION_LOGS: '/session-logs',
  SETTINGS: '/settings',
  PROFILE: '/settings/profile',
  NOT_FOUND: '/not-found',
  UNAUTHORIZED: '/unauthorized',
  SUPPLIERS: '/suppliers',
  SUPPLIERS_CREATE: '/suppliers/new',
  SUPPLIERS_EDIT: '/suppliers/:id/edit',
  SUPPLIERS_VIEW: '/suppliers/:id',
  // clients
  CLIENTS: '/clients',
  CLIENTS_CREATE: '/clients/new',
  CLIENTS_EDIT: '/clients/:id/edit',
  CLIENTS_VIEW: '/clients/:id',
  // Portfolio
  UNITS_OF_MEASURE: '/portfolio/units-of-measure',
  UNITS_OF_MEASURE_CREATE: '/portfolio/units-of-measure/new',
  UNITS_OF_MEASURE_EDIT: '/portfolio/units-of-measure/:id/edit',
  SERVICE_CATEGORIES: '/portfolio/service-categories',
  SERVICE_CATEGORIES_CREATE: '/portfolio/service-categories/new',
  SERVICE_CATEGORIES_EDIT: '/portfolio/service-categories/:id/edit',
  SERVICES: '/portfolio/services',
  SERVICES_CREATE: '/portfolio/services/new',
  SERVICES_EDIT: '/portfolio/services/:id/edit',
};

export const DEFAULT_PAGINATION = {
  PAGE: 1,
  LIMIT: 10,
};
