export const STORAGE_KEYS = {
  ACCESS_TOKEN: 'accessToken',
  REFRESH_TOKEN: 'refreshToken',
  USER: 'user',
  THEME: 'theme',
};

export const PERMISSIONS = {
  CREATE_USERS: 'create_users',
  READ_USERS: 'read_users',
  UPDATE_USERS: 'update_users',
  DELETE_USERS: 'delete_users',
  CREATE_ROLES: 'create_roles',
  READ_ROLES: 'read_roles',
  UPDATE_ROLES: 'update_roles',
  DELETE_ROLES: 'delete_roles',
  CREATE_PERMISSIONS: 'create_permissions',
  READ_PERMISSIONS: 'read_permissions',
  UPDATE_PERMISSIONS: 'update_permissions',
  DELETE_PERMISSIONS: 'delete_permissions',
  MANAGE_PERMISSIONS: 'manage_permissions',
  CREATE_AREAS: 'create_areas',
  READ_AREAS: 'read_areas',
  UPDATE_AREAS: 'update_areas',
  DELETE_AREAS: 'delete_areas',
  CREATE_CARGOS: 'create_cargos',
  READ_CARGOS: 'read_cargos',
  UPDATE_CARGOS: 'update_cargos',
  DELETE_CARGOS: 'delete_cargos',
  CREATE_PRODUCTION_AREAS: 'create_production_areas',
  READ_PRODUCTION_AREAS: 'read_production_areas',
  UPDATE_PRODUCTION_AREAS: 'update_production_areas',
  DELETE_PRODUCTION_AREAS: 'delete_production_areas',
  READ_AUDIT_LOGS: 'read_audit_logs',
  READ_SESSION_LOGS: 'read_session_logs',
  CREATE_SUPPLIERS: 'create_suppliers',
  READ_SUPPLIERS: 'read_suppliers',
  UPDATE_SUPPLIERS: 'update_suppliers',
  DELETE_SUPPLIERS: 'delete_suppliers',
  CREATE_CLIENTS: 'create_clients',
  READ_CLIENTS: 'read_clients',
  UPDATE_CLIENTS: 'update_clients',
  DELETE_CLIENTS: 'delete_clients',
  UPDATE_CLIENT_SPECIAL_CONDITION: 'update_client_special_condition',
  // Portfolio - Units of Measure
  CREATE_UNITS_OF_MEASURE: 'create_units_of_measure',
  READ_UNITS_OF_MEASURE: 'read_units_of_measure',
  UPDATE_UNITS_OF_MEASURE: 'update_units_of_measure',
  DELETE_UNITS_OF_MEASURE: 'delete_units_of_measure',
  // Portfolio - Product Categories
  CREATE_PRODUCT_CATEGORIES: 'create_product_categories',
  READ_PRODUCT_CATEGORIES: 'read_product_categories',
  UPDATE_PRODUCT_CATEGORIES: 'update_product_categories',
  DELETE_PRODUCT_CATEGORIES: 'delete_product_categories',
  // Portfolio - Products
  CREATE_PRODUCTS: 'create_products',
  READ_PRODUCTS: 'read_products',
  UPDATE_PRODUCTS: 'update_products',
  DELETE_PRODUCTS: 'delete_products',
  // Portfolio - Supply Categories
  CREATE_SUPPLY_CATEGORIES: 'create_supply_categories',
  READ_SUPPLY_CATEGORIES: 'read_supply_categories',
  UPDATE_SUPPLY_CATEGORIES: 'update_supply_categories',
  DELETE_SUPPLY_CATEGORIES: 'delete_supply_categories',
  // Portfolio - Supplies
  CREATE_SUPPLIES: 'create_supplies',
  READ_SUPPLIES: 'read_supplies',
  UPDATE_SUPPLIES: 'update_supplies',
  DELETE_SUPPLIES: 'delete_supplies',
  // Orders
  CREATE_ORDERS: 'create_orders',
  READ_ORDERS: 'read_orders',
  UPDATE_ORDERS: 'update_orders',
  DELETE_ORDERS: 'delete_orders',
  APPROVE_ORDERS: 'approve_orders',
  READ_PENDING_ORDERS: 'read_pending_orders',
  //READ_COMMERCIAL_CHANNELS
  READ_COMMERCIAL_CHANNELS: 'read_commercial_channels',
  CREATE_COMMERCIAL_CHANNELS: 'create_commercial_channels',
  UPDATE_COMMERCIAL_CHANNELS: 'update_commercial_channels',
  DELETE_COMMERCIAL_CHANNELS: 'delete_commercial_channels',
  // Quotes
  CREATE_QUOTES: 'create_quotes',
  READ_QUOTES: 'read_quotes',
  UPDATE_QUOTES: 'update_quotes',
  DELETE_QUOTES: 'delete_quotes',
  CONVERT_QUOTES: 'convert_quotes',
  // Company
  READ_COMPANY: 'read_company',
  UPDATE_COMPANY: 'update_company',
  // Work Orders
  CREATE_WORK_ORDERS: 'create_work_orders',
  READ_WORK_ORDERS: 'read_work_orders',
  UPDATE_WORK_ORDERS: 'update_work_orders',
  DELETE_WORK_ORDERS: 'delete_work_orders',
  // Expense Types
  CREATE_EXPENSE_TYPES: 'create_expense_types',
  READ_EXPENSE_TYPES: 'read_expense_types',
  UPDATE_EXPENSE_TYPES: 'update_expense_types',
  DELETE_EXPENSE_TYPES: 'delete_expense_types',
  // Expense Orders
  CREATE_EXPENSE_ORDERS: 'create_expense_orders',
  READ_EXPENSE_ORDERS: 'read_expense_orders',
  UPDATE_EXPENSE_ORDERS: 'update_expense_orders',
  DELETE_EXPENSE_ORDERS: 'delete_expense_orders',
  APPROVE_EXPENSE_ORDERS: 'approve_expense_orders',
};

export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  USERS_CREATE: '/users/create',
  USERS_EDIT: '/users/:id/edit',
  USERS_VIEW: '/users/:id',
  ROLES: '/roles',
  ROLES_CREATE: '/roles/create',
  ROLES_EDIT: '/roles/:id/edit',
  ROLES_PERMISSIONS: '/roles/:id/permissions',
  PERMISSIONS: '/permissions',
  PERMISSIONS_CREATE: '/permissions/create',
  PERMISSIONS_EDIT: '/permissions/:id/edit',
  AREAS: '/areas',
  AREAS_CREATE: '/areas/new',
  AREAS_EDIT: '/areas/:id/edit',
  AREAS_VIEW: '/areas/:id',
  CARGOS: '/cargos',
  CARGOS_CREATE: '/cargos/new',
  CARGOS_EDIT: '/cargos/:id/edit',
  CARGOS_VIEW: '/cargos/:id',
  PRODUCTION_AREAS: '/production-areas',
  PRODUCTION_AREAS_CREATE: '/production-areas/new',
  PRODUCTION_AREAS_EDIT: '/production-areas/:id/edit',
  PRODUCTION_AREAS_VIEW: '/production-areas/:id',
  AUDIT_LOGS: '/audit-logs',
  SESSION_LOGS: '/session-logs',
  SETTINGS: '/settings',
  PROFILE: '/settings/profile',
  NOT_FOUND: '/not-found',
  UNAUTHORIZED: '/unauthorized',
  SUPPLIERS: '/suppliers',
  SUPPLIERS_CREATE: '/suppliers/new',
  SUPPLIERS_EDIT: '/suppliers/:id/edit',
  SUPPLIERS_VIEW: '/suppliers/:id',
  // clients
  CLIENTS: '/clients',
  CLIENTS_CREATE: '/clients/new',
  CLIENTS_EDIT: '/clients/:id/edit',
  CLIENTS_VIEW: '/clients/:id',
  // Portfolio
  UNITS_OF_MEASURE: '/portfolio/units-of-measure',
  UNITS_OF_MEASURE_CREATE: '/portfolio/units-of-measure/new',
  UNITS_OF_MEASURE_EDIT: '/portfolio/units-of-measure/:id/edit',
  PRODUCT_CATEGORIES: '/portfolio/product-categories',
  PRODUCT_CATEGORIES_CREATE: '/portfolio/product-categories/new',
  PRODUCT_CATEGORIES_EDIT: '/portfolio/product-categories/:id/edit',
  PRODUCTS: '/portfolio/products',
  PRODUCTS_CREATE: '/portfolio/products/new',
  PRODUCTS_EDIT: '/portfolio/products/:id/edit',
  SUPPLY_CATEGORIES: '/portfolio/supply-categories',
  SUPPLY_CATEGORIES_CREATE: '/portfolio/supply-categories/new',
  SUPPLY_CATEGORIES_EDIT: '/portfolio/supply-categories/:id/edit',
  SUPPLIES: '/portfolio/supplies',
  SUPPLIES_CREATE: '/portfolio/supplies/new',
  SUPPLIES_EDIT: '/portfolio/supplies/:id/edit',
  // Orders
  ORDERS: '/orders',
  ORDERS_CREATE: '/orders/new',
  ORDERS_EDIT: '/orders/:id/edit',
  ORDERS_DETAIL: '/orders/:id',
  PENDING_PAYMENT_ORDERS: '/orders/pending-payment',
  STATUS_CHANGE_REQUESTS: '/orders/status-change-requests',
  // Order Timeline
  ORDER_FLOW: '/orders/flow/:type/:id',
  ORDER_FLOW_BASE: '/orders/flow',
  // Quotes
  QUOTES: '/quotes',
  QUOTES_CREATE: '/quotes/new',
  QUOTES_EDIT: '/quotes/:id/edit',
  QUOTES_DETAIL: '/quotes/:id',
  // Company
  COMPANY: '/company',
  // Work Orders
  WORK_ORDERS: '/work-orders',
  WORK_ORDERS_CREATE: '/work-orders/new',
  WORK_ORDERS_DETAIL: '/work-orders/:id',
  WORK_ORDERS_EDIT: '/work-orders/:id/edit',
  // Expense Orders
  EXPENSE_ORDERS: '/expense-orders',
  EXPENSE_ORDERS_CREATE: '/expense-orders/new',
  EXPENSE_ORDERS_EDIT: '/expense-orders/:id/edit',
  EXPENSE_ORDERS_DETAIL: '/expense-orders/:id',
};

export const DEFAULT_PAGINATION = {
  PAGE: 1,
  LIMIT: 10,
};
